macro(add_subdir_option name) #printname default exclude options
	if(${ARGC} GREATER  1)
		set(printname ${ARGV1})
	else()
		set(printname ${name})
	endif()
	if(${ARGC} GREATER  2)
		option(Links_${name} "Build ${printname}" ${ARGV2})
	else()
		option(Links_${name} "Build ${printname}" true)
	endif()
	if(Links_${name})
		message("Adding ${printname} to build")
		#if(${ARGC} GREATER  3)
		#	add_subdirectory(${name} ${BIN_DIR}/${name} ${ARGV3})
		#else()
			add_subdirectory(${name} ${BIN_DIR}/${name})
		#endif()
	endif()
endmacro(add_subdir_option)